version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  scrapers:
    build: ./scrapers
    depends_on:
      - db
      - redis
  ml:
    build: ./ml
    depends_on:
      - backend
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: smartshopper
      POSTGRES_PASSWORD: smartshopper
      POSTGRES_DB: smartshopper
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
